#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Main Agent for Smart Training Factory
Oversees the entire training package creation process
"""

import os
import json
from typing import Dict, List, Optional
from datetime import datetime

class MainAgent:
    """
        Main orchestrating agent for the training factory system.
            Coordinates between 5 specialized AI agents.
                """

                        def __init__(self):
                                self.name = "Main Agent"
                                        self.created_at = datetime.now()
                                                self.training_packages = []
                                                        self.agents = {
                                                                    'content': 'Content Generation Agent',
                                                                                'structure': 'Structure Planning Agent',
                                                                                            'media': 'Media Creation Agent',
                                                                                                        'assessment': 'Assessment Design Agent',
                                                                                                                    'optimization': 'Optimization Agent'
                                                                                                                            }
                                                                                                                                
                                                                                                                                    def create_training_package(self, topic: str, target_audience: str, duration_minutes: int) -> Dict:
                                                                                                                                            """
                                                                                                                                                    Create a complete training package in 45-60 minutes.
                                                                                                                                                            
                                                                                                                                                                    Args:
                                                                                                                                                                                topic (str): The training topic
                                                                                                                                                                                            target_audience (str): Target audience description
                                                                                                                                                                                                        duration_minutes (int): Desired duration in minutes
                                                                                                                                                                                                                
                                                                                                                                                                                                                        Returns:
                                                                                                                                                                                                                                    Dict: Complete training package
                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                            print(f"[{self.name}] Starting training package creation for: {topic}")
                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                            package = {
                                                                                                                                                                                                                                                                                        'id': datetime.now().strftime('%Y%m%d%H%M%S'),
                                                                                                                                                                                                                                                                                                    'topic': topic,
                                                                                                                                                                                                                                                                                                                'target_audience': target_audience,
                                                                                                                                                                                                                                                                                                                            'duration_minutes': duration_minutes,
                                                                                                                                                                                                                                                                                                                                        'created_at': datetime.now().isoformat(),
                                                                                                                                                                                                                                                                                                                                                    'agents_involved': list(self.agents.values()),
                                                                                                                                                                                                                                                                                                                                                                'content': {},
                                                                                                                                                                                                                                                                                                                                                                            'structure': {},
                                                                                                                                                                                                                                                                                                                                                                                        'media': {},
                                                                                                                                                                                                                                                                                                                                                                                                    'assessments': {}
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                            self.training_packages.append(package)
                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"[{self.name}] Package created successfully: {package['id']}")
                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                    return package
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                            def get_agent_status(self) -> Dict:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """Get status of all agents"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'main_agent': self.name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'total_packages': len(self.training_packages),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'specialized_agents': self.agents,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'system_status': 'operational'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def save_package(self, package: Dict, output_dir: str = 'output') -> str:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """Save training package to JSON file"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if not os.path.exists(output_dir):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        os.makedirs(output_dir)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        filename = f"{output_dir}/training_package_{package['id']}.json"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with open(filename, 'w', encoding='utf-8') as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            json.dump(package, f, indent=2, ensure_ascii=False)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return filename
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Example usage
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    agent = MainAgent()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Create a sample training package
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                package = agent.create_training_package(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        topic='Digital Transformation Leadership',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                target_audience='Senior Managers',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        duration_minutes=45
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Display agent status
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("\nAgent Status:")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(json.dumps(agent.get_agent_status(), indent=2, ensure_ascii=False))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Save the package
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        output_file = agent.save_package(package)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"\nPackage saved to: {output_file}")
